"""Writes firestore.rules, with the name lists taken from the Dart source.

A check that only runs in the app protects nothing: the app is what an
attacker replaces. So the server has to know which names are real, and the
only way that list stays true is to generate it from the one the game
generates names from.

    python tool/build_rules.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "lib" / "models" / "player_name.dart"
RULES = ROOT / "firestore.rules"


def block(name: str) -> str:
    """The text of one `static const _name = <...>[ ... ];` list."""
    text = SOURCE.read_text(encoding="utf-8")
    start = text.index(f"_{name} = <")
    end = text.index("];", start)
    return text[start:end]


def pairs(name: str) -> list[tuple[str, str]]:
    return re.findall(r"\['([^']+)',\s*'([^']+)'\]", block(name))


def words(name: str) -> list[str]:
    return re.findall(r"'([^']+)'", block(name).split("[", 1)[1])


def rules_list(values) -> str:
    inner = ", ".join(f"'{v}'" for v in values)
    return f"[{inner}]"


def main() -> None:
    hebrew_adjectives = pairs("hebrewAdjectives")
    hebrew_creatures = pairs("hebrewCreatures")
    english_adjectives = words("englishAdjectives")
    english_creatures = words("englishCreatures")

    masculine = [a[0] for a in hebrew_adjectives]
    feminine = [a[1] for a in hebrew_adjectives]
    he_masculine = [c[0] for c in hebrew_creatures if c[1] == "m"]
    he_feminine = [c[0] for c in hebrew_creatures if c[1] == "f"]

    text = f"""// GENERATED by tool/build_rules.py -- do not edit by hand.
//
// The name lists come from lib/models/player_name.dart, because a name is
// only real if the game could have made it, and the app cannot be trusted to
// say so: the app is the part an attacker replaces.
//
// Deploy with: firebase deploy --only firestore:rules

rules_version = '2';

service cloud.firestore {{
  match /databases/{{database}}/documents {{

    function signedIn() {{
      return request.auth != null;
    }}

    function mine(uid) {{
      return signedIn() && request.auth.uid == uid;
    }}

    // A time the game could actually have produced: a hunt runs 45 seconds at
    // most, and nobody finds her in under half of one.
    function plausible(ms) {{
      return ms is int && ms >= 500 && ms <= 120000;
    }}

    function nameWords(name) {{
      return name.split(' ');
    }}

    function nameNumber(name) {{
      return nameWords(name)[nameWords(name).size() - 1];
    }}

    // "<creature> <adjective> <number>" in Hebrew, with the adjective taking
    // the creature's gender; "<adjective> <creature> <number>" in English.
    function realName(name) {{
      return name is string
        && name.size() <= 40
        && nameNumber(name).matches('^[1-9][0-9][0-9]$')
        && (hebrewName(name) || englishName(name));
    }}

    function withoutNumber(name) {{
      return name.split(' ' + nameNumber(name))[0];
    }}

    function hebrewName(name) {{
      return (
        (nameWords(name)[0] in {rules_list(he_masculine)}
          && withoutNumber(name).split(nameWords(name)[0] + ' ')[1] in {rules_list(masculine)})
        ||
        (nameWords(name)[0] in {rules_list(he_feminine)}
          && withoutNumber(name).split(nameWords(name)[0] + ' ')[1] in {rules_list(feminine)})
      );
    }}

    function englishName(name) {{
      return nameWords(name)[0] in {rules_list(english_adjectives)}
        && withoutNumber(name).split(nameWords(name)[0] + ' ')[1] in {rules_list(english_creatures)};
    }}

    // -- the day's table ---------------------------------------------------
    //
    // One row per player per day, written once. The daily hunt allows one
    // attempt; refusing the second write here is what makes that true for a
    // client that has been modified to allow more.
    match /daily/{{day}}/scores/{{uid}} {{
      allow read: if signedIn();
      allow create: if mine(uid)
        && request.resource.data.keys().hasOnly(['name', 'ms', 'at'])
        && plausible(request.resource.data.ms)
        && realName(request.resource.data.name)
        && request.resource.data.at == request.time;
      allow update, delete: if false;
    }}

    // -- the week and all-time tables --------------------------------------
    //
    // One row per player, holding their best. A player may improve their own
    // row and nothing else, and a row can only ever get faster.
    match /players/{{uid}} {{
      allow read: if signedIn();
      allow create: if mine(uid)
        && request.resource.data.keys().hasOnly(
             ['name', 'bestMs', 'weekKey', 'weekBestMs', 'at'])
        && plausible(request.resource.data.bestMs)
        && plausible(request.resource.data.weekBestMs)
        && realName(request.resource.data.name)
        && request.resource.data.at == request.time;
      allow update: if mine(uid)
        && request.resource.data.keys().hasOnly(
             ['name', 'bestMs', 'weekKey', 'weekBestMs', 'at'])
        && plausible(request.resource.data.bestMs)
        && plausible(request.resource.data.weekBestMs)
        && realName(request.resource.data.name)
        && request.resource.data.at == request.time
        // An all-time best that grows is not a best.
        && request.resource.data.bestMs <= resource.data.bestMs
        // The week's best may only start over when the week does.
        && (request.resource.data.weekKey != resource.data.weekKey
            || request.resource.data.weekBestMs <= resource.data.weekBestMs);
      allow delete: if mine(uid);
    }}

    // Nothing else is anybody's business.
    match /{{document=**}} {{
      allow read, write: if false;
    }}
  }}
}}
"""
    RULES.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {RULES.relative_to(ROOT)}")
    print(f"  hebrew   {len(hebrew_creatures)} creatures x "
          f"{len(hebrew_adjectives)} adjectives")
    print(f"  english  {len(english_creatures)} creatures x "
          f"{len(english_adjectives)} adjectives")


if __name__ == "__main__":
    main()
